---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: spring-boot-docker
  name: spring-boot-docker
spec:
  ports:
    - port: 8080
  selector:
    app: spring-boot-docker

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-docker
spec:
  selector:
    matchLabels:
      app: spring-boot-docker
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-boot-docker
    spec:
      containers:
      - name: spring-boot-docker
        image: itstarting/spring-boot-docker
        ports:
        - containerPort: 8080